# - pyproject.toml -

[tool.black]
# How many characters per line to allow.
line-length = 79
# Don't normalize string quotes or prefixes. (e.g: replace any ' with ")
skip-string-normalization = false
# Don't use trailing commas as a reason to split lines.
skip-magic-trailing-comma = true


[tool.pylint]
fail-under = 8.5  # Fail under 8.5/10
# Expected 79 characters per line but the max allowed is 120.
max-line-length = 120
disable = [
    "C0103",  # Module name doesn't conform to snake_case naming style (invalid-name)
    "C0114",  # Missing module docstring (missing-module-docstring)
    "R0801",  # Similar lines in 2 files
    "R1725",  # Consider using Python 3 style super() without arguments
]


[tool.coverage.run]
omit = [
    # omit all files tests
    "*/tests/*",
]

include = [
    # Only include python files in this repo
    "${REZ_VFXDESKTOP_BASE}/*",
]

[tool.coverage.report]
skip_covered = true
skip_empty = true
exclude_lines = [
    "pragma: no cover",
    # Skip any pass lines such as may be used with @abstractmethod
    "pass",
    # Don't complain about missing debug-only code:
    "def __repr__",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",

    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
]
